Repository teamSynapse6/Starting_Block_Server, pull requests merged in 2024-04, with the labels that each got.

#44 feat: 로드맵에 담긴 교외 공고 리스트 조회 API 구현 (#43)
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementRepository.java
  src/main/java/com/startingblock/domain/announcement/dto/RoadmapAnnouncementRes.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
Labels: feature

#45 fix: 로드맵 교외 공고 리스트 조회 API 기간 내 공고만 조회하게 수정
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
Labels: fix

#46 fix: 로드맵 교외 공고 리스트 조회 API 기간 내 공고만 조회하게 수정
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
Labels: fix

#49 feat: 웹 api 개발, 메일 서비스 개발
  build.gradle
  src/main/java/com/startingblock/StartingBlockApplication.java
  src/main/java/com/startingblock/domain/answer/application/AnswerService.java
  src/main/java/com/startingblock/domain/answer/domain/Answer.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerRequestDto.java
  src/main/java/com/startingblock/domain/answer/presentation/AnswerController.java
  src/main/java/com/startingblock/domain/mail/application/MailService.java
  src/main/java/com/startingblock/domain/mail/dto/MailRequestDto.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/application/QuestionService.java
  src/main/java/com/startingblock/domain/question/domain/Question.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionRepository.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/question/presentation/QuestionController.java
  src/main/java/com/startingblock/domain/web/presentation/WebController.java
  src/main/resources/templates/mail.html
Labels: deploy

#51 fix: deploy script 수정
  .github/workflows/deploy.yml
Labels: fix

#52 fix: deploy script 수정
  .github/workflows/deploy.yml
Labels: deploy

#54 fix: web api 토큰 문제 수정
  src/main/java/com/startingblock/domain/question/presentation/QuestionController.java
  src/main/java/com/startingblock/global/config/security/SecurityConfig.java
Labels: fix

#55 fix: web api 토큰 문제 없도록 수정
  src/main/java/com/startingblock/domain/question/presentation/QuestionController.java
  src/main/java/com/startingblock/global/config/security/SecurityConfig.java
Labels: deploy

#57 feat: 프론트 피드백 반영
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/startingblock/domain/question/application/QuestionService.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/reply/dto/ReplyResponseDto.java
Labels: feature

#58 feat: 프론트 피드백 반영
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/startingblock/domain/question/application/QuestionService.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/reply/dto/ReplyResponseDto.java
Labels: deploy

#60 feat: K-StartUp 새로운 API 적용
  src/main/java/com/startingblock/StartingBlockApplication.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementService.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/Announcement.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementRepository.java
  src/main/java/com/startingblock/domain/announcement/presentation/AnnouncementController.java
  src/main/java/com/startingblock/global/config/AsyncConfig.java
  src/main/java/com/startingblock/global/error/ApiControllerAdvice.java
  src/main/java/com/startingblock/global/infrastructure/feign/OpenDataClient.java
  src/main/java/com/startingblock/global/infrastructure/feign/dto/NewKStartUpAnnouncementRes.java
Labels: feature

#62 feat: PDF 업로드 API 구현
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementPdfUploader.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementService.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementWriter.java
  src/main/java/com/startingblock/domain/announcement/domain/Announcement.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementRepository.java
  src/main/java/com/startingblock/domain/announcement/dto/PdfUploadReq.java
  src/main/java/com/startingblock/domain/announcement/presentation/AnnouncementController.java
  src/main/java/com/startingblock/global/infrastructure/feign/OpenDataClient.java
  src/main/java/com/startingblock/global/infrastructure/feign/PdfClient.java
  src/main/java/com/startingblock/global/infrastructure/feign/dto/NewKStartUpAnnouncementRes.java
  src/main/java/com/startingblock/global/infrastructure/feign/dto/PdfResultRes.java
  src/main/java/com/startingblock/global/infrastructure/feign/dto/PdfUploadRes.java
Labels: feature

#63 feat: 공공 데이터 API 교체 및 PDF 요청 API 구현
  src/main/java/com/startingblock/StartingBlockApplication.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementPdfUploader.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementService.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementWriter.java
  src/main/java/com/startingblock/domain/announcement/domain/Announcement.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementRepository.java
  src/main/java/com/startingblock/domain/announcement/dto/PdfUploadReq.java
  src/main/java/com/startingblock/domain/announcement/presentation/AnnouncementController.java
  src/main/java/com/startingblock/global/config/AsyncConfig.java
  src/main/java/com/startingblock/global/error/ApiControllerAdvice.java
  src/main/java/com/startingblock/global/infrastructure/feign/OpenDataClient.java
  src/main/java/com/startingblock/global/infrastructure/feign/PdfClient.java
  src/main/java/com/startingblock/global/infrastructure/feign/dto/NewKStartUpAnnouncementRes.java
  src/main/java/com/startingblock/global/infrastructure/feign/dto/PdfResultRes.java
  src/main/java/com/startingblock/global/infrastructure/feign/dto/PdfUploadRes.java
Labels: feature

#64 feat: 마이페이지 api 개발
  src/main/java/com/startingblock/domain/answer/application/AnswerFindService.java
  src/main/java/com/startingblock/domain/answer/application/AnswerService.java
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerRepository.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/startingblock/domain/answer/presentation/AnswerController.java
  src/main/java/com/startingblock/domain/heart/application/HeartFindService.java
  src/main/java/com/startingblock/domain/heart/domain/repository/HeartRepository.java
  src/main/java/com/startingblock/domain/heart/dto/HeartResponseDto.java
  src/main/java/com/startingblock/domain/heart/presentation/HeartController.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepository.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionRepository.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/question/presentation/QuestionController.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyRepository.java
Labels: feature

#65 feat: 마이페이지 api 개발
  src/main/java/com/startingblock/domain/answer/application/AnswerFindService.java
  src/main/java/com/startingblock/domain/answer/application/AnswerService.java
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerRepository.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/startingblock/domain/answer/presentation/AnswerController.java
  src/main/java/com/startingblock/domain/heart/application/HeartFindService.java
  src/main/java/com/startingblock/domain/heart/domain/repository/HeartRepository.java
  src/main/java/com/startingblock/domain/heart/dto/HeartResponseDto.java
  src/main/java/com/startingblock/domain/heart/presentation/HeartController.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepository.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionRepository.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/question/presentation/QuestionController.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyRepository.java
Labels: deploy

#66 feat: 유저 Authorization API 구현
  src/main/java/com/startingblock/domain/answer/application/AnswerFindService.java
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/auth/application/AuthService.java
  src/main/java/com/startingblock/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/startingblock/domain/auth/application/CustomUserDetailsService.java
  src/main/java/com/startingblock/domain/auth/domain/Token.java
  src/main/java/com/startingblock/domain/auth/domain/repository/TokenRepository.java
  src/main/java/com/startingblock/domain/auth/dto/SignInReq.java
  src/main/java/com/startingblock/domain/auth/dto/SignInRes.java
  src/main/java/com/startingblock/domain/auth/dto/SignUpReq.java
  src/main/java/com/startingblock/domain/auth/exception/InvalidTokenException.java
  src/main/java/com/startingblock/domain/auth/presentation/AuthController.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/user/application/UserService.java
  src/main/java/com/startingblock/domain/user/application/UserServiceImpl.java
  src/main/java/com/startingblock/domain/user/domain/Provider.java
  src/main/java/com/startingblock/domain/user/domain/User.java
  src/main/java/com/startingblock/domain/user/domain/repository/UserRepository.java
  src/main/java/com/startingblock/domain/user/dto/SignUpUserReq.java
  src/main/java/com/startingblock/domain/user/presentation/UserController.java
  src/main/java/com/startingblock/global/config/AsyncConfig.java
  src/main/java/com/startingblock/global/config/security/AuthConfig.java
Labels: feature

#67 feat: 유저 Authorization API 구현 (#66)
  src/main/java/com/startingblock/domain/answer/application/AnswerFindService.java
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/auth/application/AuthService.java
  src/main/java/com/startingblock/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/startingblock/domain/auth/application/CustomUserDetailsService.java
  src/main/java/com/startingblock/domain/auth/domain/Token.java
  src/main/java/com/startingblock/domain/auth/domain/repository/TokenRepository.java
  src/main/java/com/startingblock/domain/auth/dto/SignInReq.java
  src/main/java/com/startingblock/domain/auth/dto/SignInRes.java
  src/main/java/com/startingblock/domain/auth/dto/SignUpReq.java
  src/main/java/com/startingblock/domain/auth/exception/InvalidTokenException.java
  src/main/java/com/startingblock/domain/auth/presentation/AuthController.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/user/application/UserService.java
  src/main/java/com/startingblock/domain/user/application/UserServiceImpl.java
  src/main/java/com/startingblock/domain/user/domain/Provider.java
  src/main/java/com/startingblock/domain/user/domain/User.java
  src/main/java/com/startingblock/domain/user/domain/repository/UserRepository.java
  src/main/java/com/startingblock/domain/user/dto/SignUpUserReq.java
  src/main/java/com/startingblock/domain/user/presentation/UserController.java
  src/main/java/com/startingblock/global/config/AsyncConfig.java
  src/main/java/com/startingblock/global/config/security/AuthConfig.java
Labels: feature

#68 fix: 회원탈퇴 로직 수정
  src/main/java/com/startingblock/domain/user/application/UserServiceImpl.java
  src/main/java/com/startingblock/global/config/FeignConfig.java
  src/main/java/com/startingblock/global/infrastructure/feign/KakaoClient.java
Labels: fix

#69 fix: 회원탈퇴 로직 수정 (#68)
  src/main/java/com/startingblock/domain/user/application/UserServiceImpl.java
  src/main/java/com/startingblock/global/config/FeignConfig.java
  src/main/java/com/startingblock/global/infrastructure/feign/KakaoClient.java
Labels: fix

#70 fix: 토큰 갱신 API 로직 수정
  src/main/java/com/startingblock/domain/auth/application/AuthService.java
  src/main/java/com/startingblock/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/startingblock/domain/auth/application/CustomUserDetailsService.java
Labels: fix

#71 fix: 토큰 갱신 API 로직 수정 (#70)
  src/main/java/com/startingblock/domain/auth/application/AuthService.java
  src/main/java/com/startingblock/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/startingblock/domain/auth/application/CustomUserDetailsService.java
Labels: fix

#72 fix: 기업마당 Content도 들어가게 수정
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
Labels: fix

#73 fix: 기업마당 Content도 들어가게 수정 (#72)
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
Labels: fix
