Repository teamSynapse6/Starting_Block_Server, pull requests merged in 2024-06, with the labels that each got.

#111 feat: gpt를 사용하여 기존 질문과 비교, 그룹핑하여 담당자에게 전송 기능을 구현
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerRepository.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerRequestDto.java
  src/main/java/com/startingblock/domain/gpt/application/GptService.java
  src/main/java/com/startingblock/domain/gpt/constant/GptConstant.java
  src/main/java/com/startingblock/domain/gpt/dto/DuplicateReq.java
  src/main/java/com/startingblock/domain/gpt/dto/GptMessage.java
  src/main/java/com/startingblock/domain/gpt/dto/GptReq.java
  src/main/java/com/startingblock/domain/gpt/dto/GptRes.java
  src/main/java/com/startingblock/domain/gpt/dto/GroupingQuestionReq.java
  src/main/java/com/startingblock/domain/gpt/dto/GroupingQuestionRes.java
  src/main/java/com/startingblock/domain/gpt/dto/SimpleGPTQuestionReq.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/application/QuestionGPTService.java
  src/main/java/com/startingblock/domain/question/application/QuestionService.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionRepository.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/question/presentation/QuestionController.java
  src/main/java/com/startingblock/domain/web/presentation/WebController.java
  src/main/java/com/startingblock/global/config/RestTemplateConfig.java
Labels: feature

#112 deploy: GPT를 사용하여 질문 비교, 그룹핑하여 담당자에게 전송
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerRepository.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerRequestDto.java
  src/main/java/com/startingblock/domain/gpt/application/GptService.java
  src/main/java/com/startingblock/domain/gpt/constant/GptConstant.java
  src/main/java/com/startingblock/domain/gpt/dto/DuplicateReq.java
  src/main/java/com/startingblock/domain/gpt/dto/GptMessage.java
  src/main/java/com/startingblock/domain/gpt/dto/GptReq.java
  src/main/java/com/startingblock/domain/gpt/dto/GptRes.java
  src/main/java/com/startingblock/domain/gpt/dto/GroupingQuestionReq.java
  src/main/java/com/startingblock/domain/gpt/dto/GroupingQuestionRes.java
  src/main/java/com/startingblock/domain/gpt/dto/SimpleGPTQuestionReq.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/application/QuestionGPTService.java
  src/main/java/com/startingblock/domain/question/application/QuestionService.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionRepository.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/question/presentation/QuestionController.java
  src/main/java/com/startingblock/domain/web/presentation/WebController.java
  src/main/java/com/startingblock/global/config/RestTemplateConfig.java
Labels: deploy

#113 [Feat]]: 최종 요구사항 반영 및 공고 갱신 스케쥴링 적용
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementPdfUploader.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementWriter.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepositoryImpl.java
Labels: feature, fix

#114 [Feat]]: 최종 요구사항 반영 및 공고 갱신 스케쥴링 적용 (#113)
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementPdfUploader.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementWriter.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepositoryImpl.java
Labels: feature, fix
