Repository teamSynapse6/Starting_Block_Server, pull requests merged in 2024-05, with the labels that each got.

#74 feat: 교내 공고 크롤링, k-startup 이메일 크롤링
  build.gradle
  src/main/java/com/startingblock/domain/announcement/domain/Announcement.java
  src/main/java/com/startingblock/domain/announcement/domain/Keyword.java
  src/main/java/com/startingblock/domain/announcement/domain/University.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementRepository.java
  src/main/java/com/startingblock/domain/crawling/WebDriverManager.java
  src/main/java/com/startingblock/domain/crawling/application/CrawlingService.java
  src/main/java/com/startingblock/domain/crawling/offcampus/OffCampusCrawling.java
  src/main/java/com/startingblock/domain/crawling/offcampus/OpenData.java
  src/main/java/com/startingblock/domain/crawling/offcampus/constant/OpenDataConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/CampusAnnouncementCreator.java
  src/main/java/com/startingblock/domain/crawling/oncampus/CampusClassify.java
  src/main/java/com/startingblock/domain/crawling/oncampus/CampusCrawling.java
  src/main/java/com/startingblock/domain/crawling/oncampus/EwhaUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/HUFSUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/HanYangUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/KonKukUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/KoreaUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/KyungHeeUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/SeoulTechUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/SeoulUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/SungKyunKwanUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/YonSeiUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/EwhaConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/HUFSConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/HanYangConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/KonKukConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/KoreaConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/KyungHeeConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/SeoulConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/SeoulTechConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/SungKyunKwanConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/YonSeiConstant.java
  src/main/java/com/startingblock/domain/crawling/presentation/CrawlingController.java
Labels: feature

#76 feat: 현재 유저 정보 조회 API 구현
  src/main/java/com/startingblock/domain/announcement/domain/Announcement.java
  src/main/java/com/startingblock/domain/user/application/UserService.java
  src/main/java/com/startingblock/domain/user/application/UserServiceImpl.java
  src/main/java/com/startingblock/domain/user/domain/repository/UserRepository.java
  src/main/java/com/startingblock/domain/user/dto/UserDto.java
  src/main/java/com/startingblock/domain/user/exception/AlreadyExistNicknameException.java
  src/main/java/com/startingblock/domain/user/presentation/UserController.java
Labels: feature

#77 feat: 질문 발송 상태 조회 api
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/domain/Question.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepository.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/question/presentation/QuestionController.java
Labels: feature

#79 feat: 맞춤 공고 조회 api
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementService.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/application/CampusFindService.java
  src/main/java/com/startingblock/domain/announcement/domain/Announcement.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/dto/CustomAnnouncementRes.java
  src/main/java/com/startingblock/domain/announcement/presentation/AnnouncementController.java
Labels: feature

#80 feat: 유저 정보 조회, 크롤링, 질문 발송 상태 조회, 맞춤 공고 조회
  build.gradle
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementService.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/application/CampusFindService.java
  src/main/java/com/startingblock/domain/announcement/domain/Announcement.java
  src/main/java/com/startingblock/domain/announcement/domain/Keyword.java
  src/main/java/com/startingblock/domain/announcement/domain/University.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementRepository.java
  src/main/java/com/startingblock/domain/announcement/dto/CustomAnnouncementRes.java
  src/main/java/com/startingblock/domain/announcement/presentation/AnnouncementController.java
  src/main/java/com/startingblock/domain/crawling/WebDriverManager.java
  src/main/java/com/startingblock/domain/crawling/application/CrawlingService.java
  src/main/java/com/startingblock/domain/crawling/offcampus/OffCampusCrawling.java
  src/main/java/com/startingblock/domain/crawling/offcampus/OpenData.java
  src/main/java/com/startingblock/domain/crawling/offcampus/constant/OpenDataConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/CampusAnnouncementCreator.java
  src/main/java/com/startingblock/domain/crawling/oncampus/CampusClassify.java
  src/main/java/com/startingblock/domain/crawling/oncampus/CampusCrawling.java
  src/main/java/com/startingblock/domain/crawling/oncampus/EwhaUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/HUFSUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/HanYangUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/KonKukUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/KoreaUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/KyungHeeUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/SeoulTechUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/SeoulUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/SungKyunKwanUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/YonSeiUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/EwhaConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/HUFSConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/HanYangConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/KonKukConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/KoreaConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/KyungHeeConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/SeoulConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/SeoulTechConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/SungKyunKwanConstant.java
  src/main/java/com/startingblock/domain/crawling/oncampus/constant/YonSeiConstant.java
  src/main/java/com/startingblock/domain/crawling/presentation/CrawlingController.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/domain/Question.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepository.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/question/presentation/QuestionController.java
  src/main/java/com/startingblock/domain/user/application/UserService.java
  src/main/java/com/startingblock/domain/user/application/UserServiceImpl.java
  src/main/java/com/startingblock/domain/user/domain/repository/UserRepository.java
  src/main/java/com/startingblock/domain/user/dto/UserDto.java
  src/main/java/com/startingblock/domain/user/exception/AlreadyExistNicknameException.java
  src/main/java/com/startingblock/domain/user/presentation/UserController.java
Labels: deploy

#82 feat: 교내, 교외, 창업제도 로드맵 리스트 API 구현
  src/main/java/com/startingblock/domain/announcement/domain/AnnouncementType.java
  src/main/java/com/startingblock/domain/announcement/domain/Keyword.java
  src/main/java/com/startingblock/domain/announcement/domain/Lecture.java
  src/main/java/com/startingblock/domain/announcement/domain/University.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
Labels: feature

#83 feat: 답변을 기다리는 질문 조회 api, 맞춤 공고 조회 response 추가
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/dto/CustomAnnouncementRes.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepository.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/question/presentation/QuestionController.java
Labels: feature

#84 deploy: 교내, 교외, 창업제도 로드맵 리스트 api, 답변을 기다리는 질문 조회 api, 맞춤 공고 조회 response 추가
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/AnnouncementType.java
  src/main/java/com/startingblock/domain/announcement/domain/Keyword.java
  src/main/java/com/startingblock/domain/announcement/domain/Lecture.java
  src/main/java/com/startingblock/domain/announcement/domain/University.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/dto/CustomAnnouncementRes.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepository.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/question/presentation/QuestionController.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
Labels: deploy

#87 feat: OFF-CAMPUS 공고 조회 AI분석, 문의처 여부 컬럼 추가
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/dto/AnnouncementRes.java
Labels: feature

#88 feat: OFF-CAMPUS 공고 조회 AI분석, 문의처 여부 컬럼 추가 (#87)
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/dto/AnnouncementRes.java
Labels: feature

#90 feat: 로드맵 / 공고 관련 API 수정 및 추가
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementService.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/AnnouncementType.java
  src/main/java/com/startingblock/domain/announcement/domain/Lecture.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementRepository.java
  src/main/java/com/startingblock/domain/announcement/dto/OnCampusAnnouncementRes.java
  src/main/java/com/startingblock/domain/announcement/dto/SupportGroupRes.java
  src/main/java/com/startingblock/domain/announcement/presentation/AnnouncementController.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepository.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapAnnouncementRes.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapOnCampusRes.java
  src/main/java/com/startingblock/domain/roadmap/dto/SavedRoadmapRes.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
Labels: feature

#91 feat: 로드맵 / 공고 관련 API 수정 및 추가 (#90)
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementService.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/AnnouncementType.java
  src/main/java/com/startingblock/domain/announcement/domain/Lecture.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementRepository.java
  src/main/java/com/startingblock/domain/announcement/dto/OnCampusAnnouncementRes.java
  src/main/java/com/startingblock/domain/announcement/dto/SupportGroupRes.java
  src/main/java/com/startingblock/domain/announcement/presentation/AnnouncementController.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepository.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapAnnouncementRes.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapOnCampusRes.java
  src/main/java/com/startingblock/domain/roadmap/dto/SavedRoadmapRes.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
Labels: feature

#92 feat: 요구사항 반영
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementService.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/LectureQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/dto/AnnouncementDetailRes.java
  src/main/java/com/startingblock/domain/announcement/dto/AnnouncementRes.java
  src/main/java/com/startingblock/domain/announcement/dto/RecommendAnnouncementRes.java
  src/main/java/com/startingblock/domain/announcement/dto/RoadmapLectureRes.java
  src/main/java/com/startingblock/domain/announcement/presentation/AnnouncementController.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapLectureRepository.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
  src/main/java/com/startingblock/domain/user/application/UserService.java
  src/main/java/com/startingblock/domain/user/application/UserServiceImpl.java
  src/main/java/com/startingblock/domain/user/domain/User.java
  src/main/java/com/startingblock/domain/user/dto/SignUpUserReq.java
  src/main/java/com/startingblock/domain/user/dto/UserDto.java
  src/main/java/com/startingblock/domain/user/presentation/UserController.java
Labels: feature, fix

#93 feat: 요구사항 반영 (#92)
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementService.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/LectureQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/dto/AnnouncementDetailRes.java
  src/main/java/com/startingblock/domain/announcement/dto/AnnouncementRes.java
  src/main/java/com/startingblock/domain/announcement/dto/RecommendAnnouncementRes.java
  src/main/java/com/startingblock/domain/announcement/dto/RoadmapLectureRes.java
  src/main/java/com/startingblock/domain/announcement/presentation/AnnouncementController.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapLectureRepository.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
  src/main/java/com/startingblock/domain/user/application/UserService.java
  src/main/java/com/startingblock/domain/user/application/UserServiceImpl.java
  src/main/java/com/startingblock/domain/user/domain/User.java
  src/main/java/com/startingblock/domain/user/dto/SignUpUserReq.java
  src/main/java/com/startingblock/domain/user/dto/UserDto.java
  src/main/java/com/startingblock/domain/user/presentation/UserController.java
Labels: feature, fix

#94 feat: 요구사항 반영
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/LectureQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/LectureQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/dto/RecommendLectureRes.java
  src/main/java/com/startingblock/domain/announcement/dto/RoadmapSystemRes.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
  src/main/java/com/startingblock/domain/user/presentation/UserController.java
Labels: feature

#95 feat: 요구사항 반영 (#94)
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/LectureQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/LectureQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/dto/RecommendLectureRes.java
  src/main/java/com/startingblock/domain/announcement/dto/RoadmapSystemRes.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
  src/main/java/com/startingblock/domain/user/presentation/UserController.java
Labels: feature

#97 feat: 교내 공고 추천 API Response 수정
  build.gradle
  src/main/java/com/startingblock/domain/announcement/dto/RecommendAnnouncementRes.java
  src/main/java/com/startingblock/global/config/FeignConfig.java
Labels: feature

#98 feat: 교내 공고 추천 API Response 수정 (#97)
  build.gradle
  src/main/java/com/startingblock/domain/announcement/dto/RecommendAnnouncementRes.java
  src/main/java/com/startingblock/global/config/FeignConfig.java
Labels: feature

#99 fix: 교외 공고 추천 API 오류 해결
  src/main/java/com/startingblock/domain/announcement/dto/RecommendAnnouncementRes.java
Labels: fix

#100 fix: 교외 공고 추천 API 오류 해결 (#99)
  src/main/java/com/startingblock/domain/announcement/dto/RecommendAnnouncementRes.java
Labels: fix

#104 feat: 질문 조회 api response에 유저 프로필 번호 추가
  src/main/java/com/startingblock/domain/answer/application/AnswerFindService.java
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/reply/dto/ReplyResponseDto.java
Labels: feature

#105 feat: 내 질문, 답변 조회 response에 공고ID 추가
  src/main/java/com/startingblock/domain/answer/application/AnswerFindService.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
Labels: feature

#106 deploy: api reseponse 추가
  src/main/java/com/startingblock/domain/answer/application/AnswerFindService.java
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/reply/dto/ReplyResponseDto.java
Labels: deploy

#107 feat: 크롤링 자동화, 내 답변 조회 response에 questionId 추가
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementRepository.java
  src/main/java/com/startingblock/domain/answer/application/AnswerFindService.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/startingblock/domain/crawling/application/CrawlingService.java
  src/main/java/com/startingblock/domain/crawling/oncampus/EwhaUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/HUFSUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/HanYangUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/KonKukUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/KoreaUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/KyungHeeUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/SeoulTechUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/SeoulUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/SungKyunKwanUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/YonSeiUniv.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
Labels: feature

#108 deploy: 크롤링 자동화
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementRepository.java
  src/main/java/com/startingblock/domain/answer/application/AnswerFindService.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/startingblock/domain/crawling/application/CrawlingService.java
  src/main/java/com/startingblock/domain/crawling/oncampus/EwhaUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/HUFSUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/HanYangUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/KonKukUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/KoreaUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/KyungHeeUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/SeoulTechUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/SeoulUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/SungKyunKwanUniv.java
  src/main/java/com/startingblock/domain/crawling/oncampus/YonSeiUniv.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
Labels: deploy
