Repository teamSynapse6/Starting_Block_Server, pull requests merged in 2024-03, with the labels that each got.

#17 feat: 공고 랜덤 3개 조회 API 구현
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementService.java
  src/main/java/com/startingblock/domain/announcement/application/AnnouncementServiceImpl.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepository.java
  src/main/java/com/startingblock/domain/announcement/domain/repository/AnnouncementQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/announcement/dto/AnnouncementDetailRes.java
  src/main/java/com/startingblock/domain/announcement/presentation/AnnouncementController.java
Labels: feature

#19 chore: 공고 랜덤 3개 조회 API Swagger 수정
  src/main/java/com/startingblock/domain/announcement/presentation/AnnouncementController.java
Labels: chore

#20 chore: 공고 랜덤 3개 조회 API Swagger 수정 (#19)
  src/main/java/com/startingblock/domain/announcement/presentation/AnnouncementController.java
Labels: chore

#22 feat: 로드맵 삭제 API 구현
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/Roadmap.java
  src/main/java/com/startingblock/domain/roadmap/domain/RoadmapStatus.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapAnnouncementRepository.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepository.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapRepository.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapDetailRes.java
  src/main/java/com/startingblock/domain/roadmap/exception/NotExistsNextRoadmapException.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
Labels: feature

#23 feat: 로드맵 삭제 API 구현 (#22)
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/Roadmap.java
  src/main/java/com/startingblock/domain/roadmap/domain/RoadmapStatus.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapAnnouncementRepository.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepository.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapRepository.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapDetailRes.java
  src/main/java/com/startingblock/domain/roadmap/exception/NotExistsNextRoadmapException.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
Labels: feature

#24 feat: 로드맵 추가 API 구현
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapRepository.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapAddReq.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapDetailRes.java
  src/main/java/com/startingblock/domain/roadmap/exception/RegistrationCompletedException.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
  src/main/java/com/startingblock/global/error/ApiControllerAdvice.java
Labels: feature

#25 feat: 로드맵 추가 API 구현 (#24)
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapRepository.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapAddReq.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapDetailRes.java
  src/main/java/com/startingblock/domain/roadmap/exception/RegistrationCompletedException.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
  src/main/java/com/startingblock/global/error/ApiControllerAdvice.java
Labels: feature

#27 feat: Roadmap API 구현
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepository.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapRepository.java
  src/main/java/com/startingblock/domain/roadmap/dto/AnnouncementSavedRoadmapRes.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapAddReq.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapDetailRes.java
  src/main/java/com/startingblock/domain/roadmap/dto/SwapRoadmapReq.java
  src/main/java/com/startingblock/domain/roadmap/exception/RegistrationCompletedException.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
Labels: feature

#28 feat: Roadmap API 구현 (#27)
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapService.java
  src/main/java/com/startingblock/domain/roadmap/application/RoadmapServiceImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepository.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/roadmap/domain/repository/RoadmapRepository.java
  src/main/java/com/startingblock/domain/roadmap/dto/AnnouncementSavedRoadmapRes.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapAddReq.java
  src/main/java/com/startingblock/domain/roadmap/dto/RoadmapDetailRes.java
  src/main/java/com/startingblock/domain/roadmap/dto/SwapRoadmapReq.java
  src/main/java/com/startingblock/domain/roadmap/exception/RegistrationCompletedException.java
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
Labels: feature

#29 chore: swagger 수정
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
Labels: chore

#30 chore: swagger 수정 (#29)
  src/main/java/com/startingblock/domain/roadmap/presentation/RoadmapController.java
Labels: chore

#32 feat: 질문/답변/답글/하트 api 개발
  src/main/java/com/startingblock/domain/answer/application/AnswerService.java
  src/main/java/com/startingblock/domain/answer/domain/Answer.java
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerQuerydslRepository.java
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerRepository.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerRequestDto.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/startingblock/domain/answer/exception/InvalidAnswerException.java
  src/main/java/com/startingblock/domain/answer/presentation/AnswerController.java
  src/main/java/com/startingblock/domain/heart/application/HeartService.java
  src/main/java/com/startingblock/domain/heart/domain/Heart.java
  src/main/java/com/startingblock/domain/heart/domain/HeartType.java
  src/main/java/com/startingblock/domain/heart/domain/repository/HeartRepository.java
  src/main/java/com/startingblock/domain/heart/dto/HeartRequestDto.java
  src/main/java/com/startingblock/domain/heart/exception/InvalidHeartException.java
  src/main/java/com/startingblock/domain/heart/presentation/HeartController.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/application/QuestionService.java
  src/main/java/com/startingblock/domain/question/domain/QAType.java
  src/main/java/com/startingblock/domain/question/domain/Question.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepository.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionRepository.java
  src/main/java/com/startingblock/domain/question/dto/QuestionRequestDto.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/question/exception/InvalidQuestionException.java
  src/main/java/com/startingblock/domain/question/presentation/QuestionController.java
  src/main/java/com/startingblock/domain/reply/application/ReplyService.java
  src/main/java/com/startingblock/domain/reply/domain/Reply.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyQuerydslRepository.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyRepository.java
  src/main/java/com/startingblock/domain/reply/dto/ReplyRequestDto.java
  src/main/java/com/startingblock/domain/reply/dto/ReplyResponseDto.java
  src/main/java/com/startingblock/domain/reply/exception/InvalidReplyException.java
  src/main/java/com/startingblock/domain/reply/presentation/ReplyController.java
Labels: feature

#33 feat: 질문/답변/답글/하트 api 개발
  src/main/java/com/startingblock/domain/answer/application/AnswerService.java
  src/main/java/com/startingblock/domain/answer/domain/Answer.java
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerQuerydslRepository.java
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerRepository.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerRequestDto.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/startingblock/domain/answer/exception/InvalidAnswerException.java
  src/main/java/com/startingblock/domain/answer/presentation/AnswerController.java
  src/main/java/com/startingblock/domain/heart/application/HeartService.java
  src/main/java/com/startingblock/domain/heart/domain/Heart.java
  src/main/java/com/startingblock/domain/heart/domain/HeartType.java
  src/main/java/com/startingblock/domain/heart/domain/repository/HeartRepository.java
  src/main/java/com/startingblock/domain/heart/dto/HeartRequestDto.java
  src/main/java/com/startingblock/domain/heart/exception/InvalidHeartException.java
  src/main/java/com/startingblock/domain/heart/presentation/HeartController.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/application/QuestionService.java
  src/main/java/com/startingblock/domain/question/domain/QAType.java
  src/main/java/com/startingblock/domain/question/domain/Question.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepository.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionRepository.java
  src/main/java/com/startingblock/domain/question/dto/QuestionRequestDto.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/question/exception/InvalidQuestionException.java
  src/main/java/com/startingblock/domain/question/presentation/QuestionController.java
  src/main/java/com/startingblock/domain/reply/application/ReplyService.java
  src/main/java/com/startingblock/domain/reply/domain/Reply.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyQuerydslRepository.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyRepository.java
  src/main/java/com/startingblock/domain/reply/dto/ReplyRequestDto.java
  src/main/java/com/startingblock/domain/reply/dto/ReplyResponseDto.java
  src/main/java/com/startingblock/domain/reply/exception/InvalidReplyException.java
  src/main/java/com/startingblock/domain/reply/presentation/ReplyController.java
Labels: deploy

#34 feat: 질문 상세조회 api 컬럼 추가
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/startingblock/domain/heart/domain/repository/HeartRepository.java
  src/main/java/com/startingblock/domain/heart/exception/NotExistsHeartException.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/reply/dto/ReplyResponseDto.java
Labels: feature

#35 feat: 질문 상세 조회 api 컬럼 추가
  src/main/java/com/startingblock/domain/answer/domain/repository/AnswerQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/startingblock/domain/heart/domain/repository/HeartRepository.java
  src/main/java/com/startingblock/domain/heart/exception/NotExistsHeartException.java
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
  src/main/java/com/startingblock/domain/reply/domain/repository/ReplyQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/reply/dto/ReplyResponseDto.java
Labels: deploy

#37 fix: 질문 상세 조회 api - 하트 취소 관련 에러 수정
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
Labels: fix

#38 fix: 질문 상세 조회 시 하트 취소 관련 에러 수정
  src/main/java/com/startingblock/domain/question/application/QuestionFindService.java
Labels: fix

#40 feat: 질문 리스트 조회 api response 추가
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
Labels: feature

#41 feat: 질문 리스트 조회 api response 추가
  src/main/java/com/startingblock/domain/question/domain/repository/QuestionQuerydslRepositoryImpl.java
  src/main/java/com/startingblock/domain/question/dto/QuestionResponseDto.java
Labels: feature, deploy
